// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqNvR2SvnbJVnyP1ic0KFpNuYych91nkA',
    appId: '1:177932303936:web:27001b8059b254b17969a5',
    messagingSenderId: '177932303936',
    projectId: 'fir-96dc5',
    authDomain: 'fir-96dc5.firebaseapp.com',
    databaseURL: 'https://fir-96dc5-default-rtdb.firebaseio.com',
    storageBucket: 'fir-96dc5.firebasestorage.app',
    measurementId: 'G-GY3Z97RWNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvGOz8N3d42LYGMLAbaeL4hcbIXUNfOo0',
    appId: '1:177932303936:android:e1076cdde8b8df837969a5',
    messagingSenderId: '177932303936',
    projectId: 'fir-96dc5',
    databaseURL: 'https://fir-96dc5-default-rtdb.firebaseio.com',
    storageBucket: 'fir-96dc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl9zWxsj4xCXQyEA4u7e9VeL5Nqz9BqIo',
    appId: '1:177932303936:ios:2baeab1c188fb5477969a5',
    messagingSenderId: '177932303936',
    projectId: 'fir-96dc5',
    databaseURL: 'https://fir-96dc5-default-rtdb.firebaseio.com',
    storageBucket: 'fir-96dc5.firebasestorage.app',
    iosBundleId: 'com.example.rapidfil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl9zWxsj4xCXQyEA4u7e9VeL5Nqz9BqIo',
    appId: '1:177932303936:ios:2baeab1c188fb5477969a5',
    messagingSenderId: '177932303936',
    projectId: 'fir-96dc5',
    databaseURL: 'https://fir-96dc5-default-rtdb.firebaseio.com',
    storageBucket: 'fir-96dc5.firebasestorage.app',
    iosBundleId: 'com.example.rapidfil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqNvR2SvnbJVnyP1ic0KFpNuYych91nkA',
    appId: '1:177932303936:web:15ca4cad6f27f4377969a5',
    messagingSenderId: '177932303936',
    projectId: 'fir-96dc5',
    authDomain: 'fir-96dc5.firebaseapp.com',
    databaseURL: 'https://fir-96dc5-default-rtdb.firebaseio.com',
    storageBucket: 'fir-96dc5.firebasestorage.app',
    measurementId: 'G-K27PX1YZGG',
  );
}
